### PR TITLE
Upgraded dependencies to symfony3

### PR DESCRIPTION
**Pull request by wachterjohannes**
This PR introduces the symfony3 constraint.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot should we include symfony3 and symfony2 to the testcase? it will be also a topic for sulu

**Comment by wachterjohannes** [comment]
there seems to be a bug with the test setup. i will take a look at this later.

**Comment by danrot** [comment]
I would say we should use the `--prefer-highest` and `--prefer-lowest` arguments of composer.

**Comment by wachterjohannes** [comment]
php 5.5 with --prefer-lowest and php7.0 with --prefer-highest? and maybe an additional one php56 without a flag?

**Comment by danrot** [comment]
Well, the tests are rather short... Maybe we can also add PHP 5.6, without waiting for tests too long.

**Pull request merged**
